FROM ubuntu:16.04

RUN apt-get update && apt-get install -y doxygen graphviz

COPY doc /vuhn-bitcoin-cash-node/doc
COPY src /vuhn-bitcoin-cash-node/src

WORKDIR /vuhn-bitcoin-cash-node

RUN doxygen doc/Doxyfile

FROM nginx:alpine

COPY --from=0 /vuhn-bitcoin-cash-node/doc/doxygen/html /usr/share/nginx/html
